name: PublishCharmsToCandidate

on:
  push:
    tags:
      - "*"

jobs:
  build-charms:
    name: "Build the charms"
    runs-on: "ubuntu-20.04"
    needs: [bats, lint-charms]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run PublishCharmsToCandidate"
        run: |
          echo "Run Publish Charms To Candidate"