name: PublishCharms

on:
  pull_request:
    types: [closed]

jobs:
  build-charms:
    name: "Build the charms"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run PublishCharms"
        run: |
          echo "Run Publish Charms"