name: PublishCharmsToCandidate

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["Integration Tests"]
    branches: [master]
    types: 
      - completed

jobs:
  build-charms:
    name: "Build the charms"
    runs-on: "ubuntu-20.04"    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run PublishCharmsToCandidate"
        run: |
          echo "Run Publish Charms To Candidate"