name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

  # allow this workflow to be called from other workflows
  workflow_call:

permissions:
  contents: read

jobs:
  bats:    
    name: bats-${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:        
        os: [centos, focal]

    steps:
    - uses: actions/checkout@v3
        
    - name: "Simulate tests"
      run: |        
        echo "Running on ${{ matrix.os }}"
